apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: registry-certificate
spec:
  dnsNames:
  - {{ .Values.ingress.host }}
  secretName: registry-cert
  issuerRef:
    name: letsencrypt-cluster-issuer
    kind: ClusterIssuer
