apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-issuer"
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: registry-cert
  rules:
  - host: {{ .Values.registry.host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: registry-service
            port:
              number: {{ .Values.registry.containerPort }}
---
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: registry-ingresscontroller
spec:
  controller: k8s.io/ingress-nginx
