apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry-statefulset
  labels:
    app: registry
spec:
  serviceName: registry
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: {{ .Values.registry.image }}
        ports:
        - containerPort: {{ .Values.registry.containerPort }}
        env:
        volumeMounts:
        - name: data
          mountPath: /var/lib/registry
          readOnly: false
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: "hostpath"
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: registry-statefulset
spec:
  selector:
    app: registry
  ports:
  - protocol: TCP
    port: 5000
    targetPort: {{ .Values.registry.containerPort }}
