---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: codimd-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: codimd-certificate
spec:
  dnsNames:
  - {{ .Values.ingress.host }}
  secretName: codimd-cert
  issuerRef:
    name: codimd-issuer
