apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd-deployment
  labels:
    app: codimd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codimd
  template:
    metadata:
      labels:
        app: codimd
    spec:
      containers:
      - name: codimd
        image: hackmdio/hackmd:2.4.1
        ports:
        - containerPort: 3000
        env:
        - name: CMD_DB_URL
          valueFrom:
            secretKeyRef: { name: codimd-secret, key: connection-string }
        - name: CMD_SESSION_SECRET
          valueFrom:
            secretKeyRef: { name: codimd-secret, key: session-secret }
---
apiVersion: v1
kind: Service
metadata:
  name: codimd-service
spec:
  type: LoadBalancer
  selector:
    app: codimd
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30100
