apiVersion: apps/v1
kind: Deployment
metadata:
  name: codimd-deployment
  labels:
    app: codimd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: codimd
  template:
    metadata:
      labels:
        app: codimd
    spec:
      containers:
      - name: codimd
        image: {{ .Values.codimd.image }}
        ports:
        - containerPort: {{ .Values.codimd.containerPort }}
        env:
        - name: CMD_DB_URL
          valueFrom:
            secretKeyRef: { name: codimd-secret, key: connectionString }
        - name: CMD_SESSION_SECRET
          valueFrom:
            secretKeyRef: { name: codimd-secret, key: sessionSecret }
        # - name: CMD_PROTOCOL_USESSL
        #   value: 'true'
---
apiVersion: v1
kind: Service
metadata:
  name: codimd-service
spec:
  selector:
    app: codimd
  ports:
  - protocol: TCP
    port: 3000
    targetPort: {{ .Values.codimd.containerPort }}
