---
apiVersion: v1
kind: Secret
metadata:
  name: codimd-secret
stringData:
  postgresUser: {{ .Values.postgres.secrets.user }}
  postgresPassword: {{ .Values.postgres.secrets.password }}
  postgresDatabase: {{ .Values.postgres.secrets.database }}
  connectionString: postgres://{{ .Values.postgres.secrets.user }}:{{ .Values.postgres.secrets.password }}@postgres-service/{{ .Values.postgres.secrets.database }}
  sessionSecret: {{ .Values.codimd.secrets.sessionSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: codimd-secret-tls
type: kubernetes.io/tls
data:
  tls.crt:
  tls.key:
